### ISSUE TITLE
Update plugin

### ISSUE THREAD

**Issue by luisdev** [vfremaux/moodle-tool_sync#7]
Last version published was for Moodle 3.1.0025 (2018100100). Please could you upgrade the plugin for the curently supported versions of Moodle - 3.5 and up.

Thank you.

**Comment by vfremaux** [comment]
Hi Luid

could you precise your need ? We have here bra&nches that pushes the plugin up to 3.9 version ....

I'm just going to check they are up toi date regarding our development repos

Cheers

**Comment by luisdev** [comment]
I based my request on the information on the Moodle plugins directory, https://moodle.org/plugins/pluginversions.php?plugin=tool_sync, which says that the latest version is 3.1.0025 (2018100100) for Moodle 3.1.
I want to intall it on Moodle 3.5 and then test the site upgrade to Moodle 3.9.

**Comment by luisdev** [comment]
Ok, perhaps it's just the https://moodle.org/plugins/pluginversions.php?plugin=tool_sync page that is out of date.

I suppose for my Moodle 3.5 site I would use https://github.com/vfremaux/moodle-tool_sync/tree/MOODLE_35_STABLE

**Comment by vfremaux** [comment]
Exactly, 

We asked moodle to add an automatic package update API on moodle.org such as drupal or wordpress plugins, but this is not yet ready. And we have more than 220 plugins being supported now, So it not any more possible for us to follow all the plugins repositories accurately elsewhere than in my github.

by the way, whan an explicit request is done, i may spend a little time to do it on the requested plugin...

Cheers.
Valery

**Comment by luisdev** [comment]
Thanks. The main problem is that when I did not see an updated package on the Moodle Plugins Directory the first thing that occurred to me was that the plugin had been orphaned and was not being updated - so the first impression wasn't good.

Where is the best place to discuss this plugin?

**Comment by vfremaux** [comment]
This is the message actually published in head of the plugin :

IMPORTANT NOTE FOR PLUGIN ARCHIVE AVAILABILITY : due to the large amount of plugins supported, it is NOT affordable for us to update moodle.org packages. Please use the Source Control urls to our github to get plugins archives.

**Comment by luisdev** [comment]
As Valery explained, all versions are available from https://github.com/vfremaux/moodle-tool_sync, so closing this issue.

**Comment by luisdev** [comment]
As Valery explained, all versions are available from https://github.com/vfremaux/moodle-tool_sync, so closing this issue.
